# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MYSQL driver
#   gem install mysql2
common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: false  
  pool: 5
  username: root
  host: localhost

development:
  <<: *common
  database: panoramic_development

test:
  <<: *common
  database: panoramic_test

production:
  <<: *common
  database: panoramic_production